jobs:
  - template: ./.azure-pipelines/azure-pipelines-linux.yml


  - template: ./.azure-pipelines/azure-pipelines-osx.yml


  - template: ./.azure-pipelines/azure-pipelines-win.yml


trigger:
  - ecell4_base
